// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("cartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartItemId"));

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("cartItemId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            cartItemId = 1,
                            dateAdded = new DateTime(2025, 10, 19, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 3,
                            quantity = 1,
                            userId = 1
                        },
                        new
                        {
                            cartItemId = 2,
                            dateAdded = new DateTime(2025, 10, 19, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 4,
                            quantity = 2,
                            userId = 2
                        },
                        new
                        {
                            cartItemId = 3,
                            dateAdded = new DateTime(2025, 10, 20, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 5,
                            quantity = 1,
                            userId = 3
                        },
                        new
                        {
                            cartItemId = 4,
                            dateAdded = new DateTime(2025, 10, 17, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 6,
                            quantity = 3,
                            userId = 4
                        },
                        new
                        {
                            cartItemId = 5,
                            dateAdded = new DateTime(2025, 10, 18, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 7,
                            quantity = 1,
                            userId = 5
                        },
                        new
                        {
                            cartItemId = 6,
                            dateAdded = new DateTime(2025, 10, 16, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 8,
                            quantity = 2,
                            userId = 6
                        },
                        new
                        {
                            cartItemId = 7,
                            dateAdded = new DateTime(2025, 10, 15, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 9,
                            quantity = 1,
                            userId = 7
                        },
                        new
                        {
                            cartItemId = 8,
                            dateAdded = new DateTime(2025, 10, 14, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 10,
                            quantity = 1,
                            userId = 8
                        },
                        new
                        {
                            cartItemId = 9,
                            dateAdded = new DateTime(2025, 10, 13, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 1,
                            quantity = 1,
                            userId = 9
                        },
                        new
                        {
                            cartItemId = 10,
                            dateAdded = new DateTime(2025, 10, 12, 8, 50, 13, 0, DateTimeKind.Utc),
                            productId = 2,
                            quantity = 1,
                            userId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            categoryDescription = "Devices and gadgets",
                            categoryName = "Electronics"
                        },
                        new
                        {
                            categoryId = 2,
                            categoryDescription = "Printed and digital books",
                            categoryName = "Books"
                        },
                        new
                        {
                            categoryId = 3,
                            categoryDescription = "Apparel for men and women",
                            categoryName = "Clothing"
                        },
                        new
                        {
                            categoryId = 4,
                            categoryDescription = "Home and kitchen",
                            categoryName = "Home"
                        },
                        new
                        {
                            categoryId = 5,
                            categoryDescription = "Toys and games",
                            categoryName = "Toys"
                        },
                        new
                        {
                            categoryId = 6,
                            categoryDescription = "Sporting goods",
                            categoryName = "Sports"
                        },
                        new
                        {
                            categoryId = 7,
                            categoryDescription = "Beauty and personal care",
                            categoryName = "Beauty"
                        },
                        new
                        {
                            categoryId = 8,
                            categoryDescription = "Garden and outdoor",
                            categoryName = "Garden"
                        },
                        new
                        {
                            categoryId = 9,
                            categoryDescription = "Automotive parts and accessories",
                            categoryName = "Automotive"
                        },
                        new
                        {
                            categoryId = 10,
                            categoryDescription = "Healthcare products",
                            categoryName = "Health"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("totalAmount")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("userId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            orderId = 1,
                            createdDate = new DateTime(2025, 10, 11, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Completed",
                            totalAmount = 150,
                            userId = 1
                        },
                        new
                        {
                            orderId = 2,
                            createdDate = new DateTime(2025, 10, 12, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Processing",
                            totalAmount = 299,
                            userId = 2
                        },
                        new
                        {
                            orderId = 3,
                            createdDate = new DateTime(2025, 10, 13, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Shipped",
                            totalAmount = 45,
                            userId = 3
                        },
                        new
                        {
                            orderId = 4,
                            createdDate = new DateTime(2025, 10, 14, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Completed",
                            totalAmount = 89,
                            userId = 4
                        },
                        new
                        {
                            orderId = 5,
                            createdDate = new DateTime(2025, 10, 15, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Cancelled",
                            totalAmount = 19,
                            userId = 5
                        },
                        new
                        {
                            orderId = 6,
                            createdDate = new DateTime(2025, 10, 16, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Processing",
                            totalAmount = 60,
                            userId = 6
                        },
                        new
                        {
                            orderId = 7,
                            createdDate = new DateTime(2025, 10, 17, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Completed",
                            totalAmount = 120,
                            userId = 7
                        },
                        new
                        {
                            orderId = 8,
                            createdDate = new DateTime(2025, 10, 18, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Shipped",
                            totalAmount = 230,
                            userId = 8
                        },
                        new
                        {
                            orderId = 9,
                            createdDate = new DateTime(2025, 10, 19, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Completed",
                            totalAmount = 15,
                            userId = 9
                        },
                        new
                        {
                            orderId = 10,
                            createdDate = new DateTime(2025, 10, 20, 8, 50, 13, 0, DateTimeKind.Utc),
                            status = "Processing",
                            totalAmount = 75,
                            userId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("orderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderItemId"));

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("orderItemId");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            orderItemId = 1,
                            orderId = 1,
                            price = 699.99m,
                            productId = 1,
                            quantity = 1
                        },
                        new
                        {
                            orderItemId = 2,
                            orderId = 2,
                            price = 1199.50m,
                            productId = 2,
                            quantity = 1
                        },
                        new
                        {
                            orderItemId = 3,
                            orderId = 3,
                            price = 14.99m,
                            productId = 3,
                            quantity = 2
                        },
                        new
                        {
                            orderItemId = 4,
                            orderId = 4,
                            price = 19.99m,
                            productId = 4,
                            quantity = 3
                        },
                        new
                        {
                            orderItemId = 5,
                            orderId = 5,
                            price = 49.99m,
                            productId = 5,
                            quantity = 1
                        },
                        new
                        {
                            orderItemId = 6,
                            orderId = 6,
                            price = 29.99m,
                            productId = 6,
                            quantity = 1
                        },
                        new
                        {
                            orderItemId = 7,
                            orderId = 7,
                            price = 89.99m,
                            productId = 7,
                            quantity = 1
                        },
                        new
                        {
                            orderItemId = 8,
                            orderId = 8,
                            price = 24.99m,
                            productId = 8,
                            quantity = 2
                        },
                        new
                        {
                            orderItemId = 9,
                            orderId = 9,
                            price = 34.99m,
                            productId = 9,
                            quantity = 1
                        },
                        new
                        {
                            orderItemId = 10,
                            orderId = 10,
                            price = 12.99m,
                            productId = 10,
                            quantity = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentId"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentId");

                    b.HasIndex("orderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            paymentId = 1,
                            amount = 150m,
                            createdAt = new DateTime(2025, 10, 11, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 1,
                            status = "Paid"
                        },
                        new
                        {
                            paymentId = 2,
                            amount = 299m,
                            createdAt = new DateTime(2025, 10, 12, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 2,
                            status = "Pending"
                        },
                        new
                        {
                            paymentId = 3,
                            amount = 45m,
                            createdAt = new DateTime(2025, 10, 13, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "PayPal",
                            orderId = 3,
                            status = "Paid"
                        },
                        new
                        {
                            paymentId = 4,
                            amount = 89m,
                            createdAt = new DateTime(2025, 10, 14, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 4,
                            status = "Paid"
                        },
                        new
                        {
                            paymentId = 5,
                            amount = 19m,
                            createdAt = new DateTime(2025, 10, 15, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 5,
                            status = "Refunded"
                        },
                        new
                        {
                            paymentId = 6,
                            amount = 60m,
                            createdAt = new DateTime(2025, 10, 16, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "PayPal",
                            orderId = 6,
                            status = "Pending"
                        },
                        new
                        {
                            paymentId = 7,
                            amount = 120m,
                            createdAt = new DateTime(2025, 10, 17, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 7,
                            status = "Paid"
                        },
                        new
                        {
                            paymentId = 8,
                            amount = 230m,
                            createdAt = new DateTime(2025, 10, 18, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 8,
                            status = "Paid"
                        },
                        new
                        {
                            paymentId = 9,
                            amount = 15m,
                            createdAt = new DateTime(2025, 10, 19, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "PayPal",
                            orderId = 9,
                            status = "Paid"
                        },
                        new
                        {
                            paymentId = 10,
                            amount = 75m,
                            createdAt = new DateTime(2025, 10, 20, 8, 50, 13, 0, DateTimeKind.Utc),
                            method = "Card",
                            orderId = 10,
                            status = "Pending"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockQuantity")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            category = "Electronics",
                            categoryId = 1,
                            description = "Latest smartphone",
                            name = "Smartphone",
                            price = 699.99m,
                            stockQuantity = 50
                        },
                        new
                        {
                            productId = 2,
                            category = "Electronics",
                            categoryId = 1,
                            description = "Lightweight laptop",
                            name = "Laptop",
                            price = 1199.50m,
                            stockQuantity = 30
                        },
                        new
                        {
                            productId = 3,
                            category = "Books",
                            categoryId = 2,
                            description = "Bestselling novel",
                            name = "Novel",
                            price = 14.99m,
                            stockQuantity = 200
                        },
                        new
                        {
                            productId = 4,
                            category = "Clothing",
                            categoryId = 3,
                            description = "Cotton t-shirt",
                            name = "T-Shirt",
                            price = 19.99m,
                            stockQuantity = 150
                        },
                        new
                        {
                            productId = 5,
                            category = "Home",
                            categoryId = 4,
                            description = "Kitchen blender",
                            name = "Blender",
                            price = 49.99m,
                            stockQuantity = 40
                        },
                        new
                        {
                            productId = 6,
                            category = "Toys",
                            categoryId = 5,
                            description = "Family board game",
                            name = "Board Game",
                            price = 29.99m,
                            stockQuantity = 80
                        },
                        new
                        {
                            productId = 7,
                            category = "Sports",
                            categoryId = 6,
                            description = "Comfort running shoes",
                            name = "Running Shoes",
                            price = 89.99m,
                            stockQuantity = 60
                        },
                        new
                        {
                            productId = 8,
                            category = "Beauty",
                            categoryId = 7,
                            description = "Moisturizing cream",
                            name = "Skin Cream",
                            price = 24.99m,
                            stockQuantity = 120
                        },
                        new
                        {
                            productId = 9,
                            category = "Garden",
                            categoryId = 8,
                            description = "Durable hose",
                            name = "Garden Hose",
                            price = 34.99m,
                            stockQuantity = 70
                        },
                        new
                        {
                            productId = 10,
                            category = "Health",
                            categoryId = 10,
                            description = "Daily multivitamins",
                            name = "Vitamins",
                            price = 12.99m,
                            stockQuantity = 300
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reviw", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("reviewId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("Reviws");

                    b.HasData(
                        new
                        {
                            reviewId = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Excellent",
                            productId = 1,
                            rating = 5,
                            userId = 1
                        },
                        new
                        {
                            reviewId = 2,
                            CreatedAt = new DateTime(2025, 10, 2, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Very good",
                            productId = 2,
                            rating = 4,
                            userId = 2
                        },
                        new
                        {
                            reviewId = 3,
                            CreatedAt = new DateTime(2025, 10, 3, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Average",
                            productId = 3,
                            rating = 3,
                            userId = 3
                        },
                        new
                        {
                            reviewId = 4,
                            CreatedAt = new DateTime(2025, 10, 4, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Nice",
                            productId = 4,
                            rating = 5,
                            userId = 4
                        },
                        new
                        {
                            reviewId = 5,
                            CreatedAt = new DateTime(2025, 10, 5, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Not great",
                            productId = 5,
                            rating = 2,
                            userId = 5
                        },
                        new
                        {
                            reviewId = 6,
                            CreatedAt = new DateTime(2025, 10, 6, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Good",
                            productId = 6,
                            rating = 4,
                            userId = 6
                        },
                        new
                        {
                            reviewId = 7,
                            CreatedAt = new DateTime(2025, 10, 7, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Love it",
                            productId = 7,
                            rating = 5,
                            userId = 7
                        },
                        new
                        {
                            reviewId = 8,
                            CreatedAt = new DateTime(2025, 10, 8, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Okay",
                            productId = 8,
                            rating = 3,
                            userId = 8
                        },
                        new
                        {
                            reviewId = 9,
                            CreatedAt = new DateTime(2025, 10, 9, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Useful",
                            productId = 9,
                            rating = 4,
                            userId = 9
                        },
                        new
                        {
                            reviewId = 10,
                            CreatedAt = new DateTime(2025, 10, 10, 8, 50, 13, 0, DateTimeKind.Utc),
                            comment = "Recommended",
                            productId = 10,
                            rating = 5,
                            userId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            createdAt = new DateTime(2025, 9, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "alice@example.com",
                            password = "pass1",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "alice"
                        },
                        new
                        {
                            userId = 2,
                            createdAt = new DateTime(2025, 9, 22, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "bob@example.com",
                            password = "pass2",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "bob"
                        },
                        new
                        {
                            userId = 3,
                            createdAt = new DateTime(2025, 9, 23, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "carol@example.com",
                            password = "pass3",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "carol"
                        },
                        new
                        {
                            userId = 4,
                            createdAt = new DateTime(2025, 9, 24, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "dave@example.com",
                            password = "pass4",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "dave"
                        },
                        new
                        {
                            userId = 5,
                            createdAt = new DateTime(2025, 9, 25, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "eve@example.com",
                            password = "pass5",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "eve"
                        },
                        new
                        {
                            userId = 6,
                            createdAt = new DateTime(2025, 9, 26, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "frank@example.com",
                            password = "pass6",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "frank"
                        },
                        new
                        {
                            userId = 7,
                            createdAt = new DateTime(2025, 9, 27, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "grace@example.com",
                            password = "pass7",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "grace"
                        },
                        new
                        {
                            userId = 8,
                            createdAt = new DateTime(2025, 9, 28, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "heidi@example.com",
                            password = "pass8",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "heidi"
                        },
                        new
                        {
                            userId = 9,
                            createdAt = new DateTime(2025, 9, 29, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "ivan@example.com",
                            password = "pass9",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "ivan"
                        },
                        new
                        {
                            userId = 10,
                            createdAt = new DateTime(2025, 9, 30, 8, 50, 13, 0, DateTimeKind.Utc),
                            email = "judy@example.com",
                            password = "pass10",
                            updatedAt = new DateTime(2025, 10, 21, 8, 50, 13, 0, DateTimeKind.Utc),
                            userName = "judy"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Reviw", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
